name: Building CI/CD pipelines using Actions

on:
  push:
    branches: [learn-ci/cd]

jobs:
   firstjob:
      runs-on: ubuntu-latest
      
      steps:
      
      - name: Git Checkout
        uses: actions/checkout@v3
      
      - name: firstjob step@2
        run: echo "hello-world"
      - name: run multi-line script
        run: |
          echo "Adding line to step#2"
          echo "yayy!! playing with github actions"

   secondjob:
      runs-on: ubuntu-latest
      needs: firstjob
      steps:
      - name: Run a normal script
        run: echo "hello-world from job-2"


