name: Using sonarqube for DeveloperFolio

on:
  push:
    branches:
    - fahid
jobs:
  sonarqubejob:
    runs-on: ubuntu-latest
    name: sonarqubetesting job

    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: SonarQube for Static Code Analysis
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      with:
        args: >
          -Dsonar.organization=muhammadfahid12  
          -Dsonar.projectKey=developerFolio
          -Dsonar.host.url=https://sonarcloud.io

